spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 12345
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true